version: "3"

services:
  app:
    build:
      dockerfile: ./Dockerfile
      context: .
    container_name: app
    volumes:
      - .:/var/www/app
    ports:
      - 8080:8080
    environment:
      - APP_ENV=dev
      - XDEBUG_ENABLED=true
    networks:
      - mysql_net
networks:
  mysql_net:
    external: true
